name: temperature_upload
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  flutter_blue_plus: ^1.35.5
  provider: ^6.1.5
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  path: ^1.9.1
  open_filex: ^4.7.0
  device_info_plus: ^11.5.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_01.png"
  min_sdk_android: 21
  remove_alpha_ios: true