name: temperature_upload
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  flutter_blue_plus: ^1.35.5
  provider: ^6.1.5
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  path: ^1.9.1
  open_filex: ^4.7.0
  device_info_plus: ^11.5.0
  shared_preferences: ^2.5.3
  flutter_foreground_task: ^9.1.0
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy/Paperlogy-1Thin.ttf
          weight: 100

        - asset: assets/fonts/Paperlogy/Paperlogy-2ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Paperlogy/Paperlogy-3Light.ttf
          weight: 300

        - asset: assets/fonts/Paperlogy/Paperlogy-4Regular.ttf
          weight: 400

        - asset: assets/fonts/Paperlogy/Paperlogy-5Medium.ttf
          weight: 500

        - asset: assets/fonts/Paperlogy/Paperlogy-6SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Paperlogy/Paperlogy-7Bold.ttf
          weight: 700

        - asset: assets/fonts/Paperlogy/Paperlogy-8ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Paperlogy/Paperlogy-9Black.ttf
          weight: 900

    - family: SCDream
      fonts:
        - asset: assets/fonts/SCDream/SCDream1.otf
          weight: 100

        - asset: assets/fonts/SCDream/SCDream2.otf
          weight: 200

        - asset: assets/fonts/SCDream/SCDream3.otf
          weight: 300

        - asset: assets/fonts/SCDream/SCDream4.otf
          weight: 400

        - asset: assets/fonts/SCDream/SCDream5.otf
          weight: 500

        - asset: assets/fonts/SCDream/SCDream6.otf
          weight: 600

        - asset: assets/fonts/SCDream/SCDream7.otf
          weight: 700

        - asset: assets/fonts/SCDream/SCDream8.otf
          weight: 800

        - asset: assets/fonts/SCDream/SCDream9.otf
          weight: 900



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_01.png"
  min_sdk_android: 21
  remove_alpha_ios: true